### ISSUE TITLE
Error with OpenAPI

### ISSUE THREAD

**Issue by Brian-McBride** [kbkk/abitia#33]
https://github.com/kbkk/abitia/blob/8a28199e08afe0234597f0f053c40c9ab1d958f3/packages/zod-dto/src/OpenApi/zodTypeToOpenApi.ts#L25

I think that the `t` variable is no longer on the zod object.

**Comment by kbkk** [comment]
Hi,

Thanks for reporting this. This library was built on top of zod 3 alpha and indeed a lot has changed since then. 

I bumped zod to 3.0.2 and tested against an application using zod 3.0.2 and 3.5.1 - so far it seems to work fine.

I released `@abitia/zod-dto@0.2.0` to npm, please try it out.
