### ISSUE TITLE
Swagger schema validation error

### ISSUE THREAD

**Issue by rafakwolf** [kbkk/abitia#45]
That line:
https://github.com/kbkk/abitia/blob/master/packages/zod-dto/src/OpenApi/zodTypeToOpenApi.ts#L30C12-L30C28

is leading the schema to have that error:
```
Structural error at components.schemas.LiveModel.required
should be an array of property names required within an object schema
Jump to line 2275
```

![image](https://github.com/kbkk/abitia/assets/2060578/ce6cbf25-ddd8-4541-85dd-79b7a859ed2c)

**Comment by eberhm** [comment]
I have the same issue. As per the [schema reference](https://swagger.io/specification/#schema-object) it seems like it should be an array of property names: https://json-schema.org/draft/2020-12/json-schema-validation#name-required

@kbkk, my intention is to create a PR addressing this issue as I want to use this package in combination with https://www.npmjs.com/package/openapi-diff. Would you be interested in such addition? Thanks!

**Comment by kbkk** [comment]
Hi,

Sorry I barely have to maintain this.

You're better off using a pkg like: https://github.com/anatine/zod-plugins/tree/main/packages/zod-nestjs

Cheers
